### ISSUE TITLE
Date entry should be in minutes, rather than seconds as the server doesn't actually use the seconds for anything!

### ISSUE THREAD

**Issue by GreenJon902** [GreenJon902/HisDoc#10]
This error was thrown as a result 
```
java.lang.RuntimeException: An error occurred,
query=
{code=6ayGTQx}


	at HisDoc-1.0.0.jar//com.greenjon902.hisdoc.pages.AddEventSubmitPageRenderer.render(AddEventSubmitPageRenderer.java:39)
	at HisDoc-1.0.0.jar//com.greenjon902.hisdoc.webDriver.HttpHandlerImpl.handle(WebDriver.java:102)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:851)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:818)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:201)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:561)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:527)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
	at HisDoc-1.0.0.jar//com.greenjon902.hisdoc.pages.AddEventSubmitPageRenderer$SubmittedEvent.convertTimestampSeparators(AddEventSubmitPageRenderer.java:120)
	at HisDoc-1.0.0.jar//com.greenjon902.hisdoc.pages.AddEventSubmitPageRenderer$SubmittedEvent.fromPost(AddEventSubmitPageRenderer.java:98)
	at HisDoc-1.0.0.jar//com.greenjon902.hisdoc.pages.AddEventSubmitPageRenderer.render(AddEventSubmitPageRenderer.java:34)
	... 11 more
```

**Comment by GreenJon902** [comment]
Fixed in [`b7b941c`](https://github.com/GreenJon902/HisDoc/commit/b7b941c44235ed858b85186dcd56e274e4cb2a41)
